### ISSUE TITLE
关于用Servlet输出流的文件下载出错

### ISSUE THREAD

**Issue by PSilverQ** [Othershe/DUtil#10]
实际情况不可能把服务器上的文件目录全部映射到服务器，所以我在tomcat服务器上映射一个下载文件的servlet ,用流读取文件，然后用response的输出给客户端。这种方式浏览器，下载工具都能正常下载。但是使用Dutil下载到快结束时总是出错，下载不成功。
我服务端是这样写的：
	File tagetFile = new File(filePath);
		if (tagetFile.exists()) {
			try {
				resp.reset();
				resp.setContentType("application/x-download");
				resp.setHeader("Last-Modified",new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(tagetFile.lastModified()));
				resp.setCharacterEncoding("utf-8");
				resp.setHeader("Content-Disposition", "attachment; filename=" + fileName + "");
				resp.setHeader("Content-Length", tagetFile.length() + "");
				/* 如果文件长度大于0 */
				if (tagetFile.length() != 0) {
					/* 创建输入流 */
					InputStream inStream = new FileInputStream(tagetFile);
					byte[] buf = new byte[4096];
					/* 创建输出流 */
					ServletOutputStream servletOS = resp.getOutputStream();
					int readLength;
					while (((readLength = inStream.read(buf)) != -1)) {
						servletOS.write(buf, 0, readLength);
					}
					inStream.close();
					servletOS.flush();
					servletOS.close();
				}
			} catch (Exception e) {
				System.out.println("FileDownLoad 错误");
			}
              }

**Comment by PSilverQ** [comment]
果然，我又尝试换一个800MB的大文件进行测试，无论大文件还是小文件都是下到最后一点点的时候，出错了，不能完整的下完。Android客户端没有报异常，倒是我的服务端报了异常，正在为课程设计奋斗，能帮我指出是什么问题吗？但是我用浏览器下载却没有问题？

org.apache.catalina.connector.ClientAbortException: java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
FileDownLoad 错误
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:356)
	at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:815)
	at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:720)
	at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:391)
	at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:369)
...............................................
aused by: java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1267)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:670)
	at org.apache.tomcat.util.net.SocketWrapperBase.writeBlocking(SocketWrapperBase.java:450)
	at org.apache.tomcat.util.net.SocketWrapperBase.write(SocketWrapperBase.java:388)
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.doWrite(Http11OutputBuffer.java:644)
	at org.apache.coyote.http11.filters.IdentityOutputFilter.doWrite(IdentityOutputFilter.java:119)
	at org.apache.coyote.http11.Http11OutputBuffer.doWrite(Http11OutputBuffer.java:235)
	at org.apache.coyote.Response.doWrite(Response.java:541)
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:351)
	... 37 more
